version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: jenkins/scripts/install_dependencies.sh
      timeout: 300
  ApplicationStop:
    - location: jenkins/scripts/stop_server.sh
      timeout: 300
  ApplicationStart:
    - location: jenkins/scripts/start_server.sh
      timeout: 300
